export const T = {
  bg: "var(--background)",
  bgSoft: "var(--background-soft)",
  card: "var(--card)",
  elevated: "var(--elevated)",
  sidebar: "var(--sidebar)",
  border: "var(--border)",
  borderSoft: "var(--border-soft)",
  purple: "var(--accent-violet)",
  purpleLight: "var(--accent-violet-soft)",
  purpleGrad: "var(--accent-dark)",
  pink: "var(--accent-rose)",
  cyan: "var(--accent-blue-soft)",
  green: "var(--accent-green)",
  amber: "var(--accent-amber)",
  orange: "var(--accent-rose)",
  orangeGrad: "var(--accent-amber)",
  red: "var(--danger)",
  blue: "var(--accent-blue)",
  text: "var(--foreground)",
  textMuted: "var(--foreground-muted)",
  textDim: "var(--foreground-dim)",
  white: "#FFFFFF",
};
